### ISSUE TITLE
Cocoapods support

### ISSUE THREAD

**Issue by ararog** [melvitax/AFDateHelper#4]
Hi, I tried to find the library from cocoapods.org search engine, but no success.

Is there any missing step, like push a release?

**Comment by matteocrippa** [comment]
it seems that the problem could be related to the plus (+) inside the name of the file, I managed to have it working adding it manually and renaming the file

**Comment by prsolucoes** [comment]
I want use with cocoapods, but not find. How to use it with cocoapods?

**Comment by codyhazelwood** [comment]
There are a couple of issues preventing this from working with CocoaPods as it is.  The podspec doesn't pass linting, the versioning needs to be changed to semantic, a branch needs to be created for with a release version, and the iOS deployment target needs to be set to 8.0.

I've forked the project here: https://github.com/codyhazelwood/AFDateHelper/.  Everything has been updated so that `pod spec lint` runs successfully, and I can import it to a test project locally (see here: https://guides.cocoapods.org/making/making-a-cocoapod.html).

I also added the AFDateHelper.h file needed for the framework to be imported.  However, when testing locally, it seems that Extensions on NSDate in a framework aren't accessible outside the framework.  Does anybody have any suggestions on fixing that?

Also, as @matteocrippa mentioned, just copying and pasting the 1 swift file into your project works for now.

**Comment by melvitax** [comment]
I've added the repo to Cocoa Pods and added a new branch supporting Swift 2.

**Comment by milankamilya** [comment]
Hi Melvitax,

Thanks for the awesome library, is really helpful to develop app fast.
I found that you suggested same pods library for swift 1.2 and swift 2.0. 
I am using AFDateHelper with swift 1.2 project. I found following error recently.

dyld: Library not loaded: @rpath/AFDateHelper.framework/AFDateHelper
  Referenced from: /private/var/mobile/Containers/Bundle/Application/3ADEC34B-B48F-4F94-959C-EB3C974D169C/Example.app/Example
  Reason: Incompatible library version: Example requires version 2.0.0 or later, but AFDateHelper provides version 1.0.
